config/routes.rb
Rails.application.routes.draw do
  resources :user_skills

  resources :profiles do
    collection do
      post :test
    end
  end

  devise_for :users, controllers: { registrations: "registrations" }

  # Defines the root path route ("/")
  root "profiles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/skill.rb
class Skill < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_many :users, through: :user_skills
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_skills, dependent: :destroy
  has_many :skills, through: :user_skills

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/models/user_skill.rb
class UserSkill < ApplicationRecord
  belongs_to :user
  belongs_to :skill
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from ActionController::Redirecting::UnsafeRedirectError do
    redirect_to root_url
  end

  protected

  public def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:about_me])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number])
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def test
    id = params[:skill_id].to_i
    @users = Skill.find(id).users
    puts "AAAAAAAAAAAAAAAA #{@users}"
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(
          'users',
          partial: 'profiles/search_result',
          locals: {users: @users}
        )
      end
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource)
    'root_path' # Or :prefix_to_your_route
  end

  def after_inactive_sign_up_path_for(resource)
    'root_path' # Or :prefix_to_your_route
  end
end

app/controllers/user_skills_controller.rb
class UserSkillsController < ApplicationController

  # GET /user_skills or /user_skills.json
  def index
    @user_skills = current_user.user_skills.order(created_at: :desc)
  end

  # POST /user_skills or /user_skills.json
  def create
    @user_skill = UserSkill.new(user_skill_params)
    @user_skill.save
    render turbo_stream: turbo_stream.prepend('user_skills',
                                          partial: "user_skills/user_skill",
                                          locals: {user_skill: @user_skill})
  end

  # DELETE /user_skills/1 or /user_skills/1.json
  def destroy
    @user_skill = UserSkill.find(params[:id])
    @user_skill.destroy
    render turbo_stream: turbo_stream.remove(@user_skill)
  end

  private
    # Only allow a list of trusted parameters through.
    def user_skill_params
      params.require(:user_skill).permit(:user_id, :skill_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]

  def index
    @users = User.all
  end

  # GET /horses/1 or /horses/1.json
  def show
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/layouts/_bottom_navbar.html.erb
<nav class="navbar fixed-bottom navbar-light d-lg-none " style="background: #C8E0F4">
  <div class="row container-fluid w-100 text-center m-1 p-0" >
    <div class="col p-1">
      <%= link_to root_path, class: "p-3 nav-icon" do %>
        <span class="material-icons">home</span>
      <% end %>
    </div>

    <div class="col p-1">
      <% if current_user %>
        <%= link_to user_skills_path, class:"p-3 nav-icon" do %>
          <span class="material-icons">star</span>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class:"p-3 nav-icon" do %>
          <span class="material-icons">star</span>
        <% end %>
      <% end %>
    </div>

    <div class="col p-1">
      <%= link_to edit_user_registration_path, class:"p-3 nav-icon" do %>
        <span class="material-icons">person</span>
      <% end %>
    </div>
  </div>

</nav>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #B8DEF4">
  <%= link_to "Rent-a-Service", root_path , class: "navbar-brand" %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto" style="margin-left: 20px">
      <li class="nav-item" style="margin-right: 14px">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>

      <li class="nav-item" style="margin-right: 14px">
        <% if current_user %>
          <%= link_to "My skills", user_skills_path, class: "nav-link" %>
        <% else %>
          <%= link_to "My skills", new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>

      <li class="nav-item" style="margin-right: 14px">
        <% if current_user %>
          <%= link_to "My account", edit_user_registration_path, class: "nav-link" %>
        <% else %>
          <%= link_to "My account", new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>

    </ul>
  </div>

  <div>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= button_to "sign out", destroy_user_session_path, method: :delete , class: "btn btn-secondary" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path , class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentAService</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <!-- Google material icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" >

  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/bottom_navbar' %>
    <% if user_signed_in? %>
      hi <%= current_user.first_name %> -
    <% end %>
    <%= Time.zone.now.strftime("%H:%M:%S") %>
    <br>

    <div id="main-container" class="container mb-5 mb-lg-0" >
      <div id="main-row" class="row">
        <div id="left-col" class="col-0 col-md-2 p-0 m-0">
        </div>
        <div id="center-col" class="col">
          <div id="yield-container" class="container">
            <%= yield %>
          </div>
        </div>
        <div id="right-col" class="col-0 col-md-2 p-0 m-0">
        </div>
      </div>
    </div>

  </body>
</html>

app/views/profiles/_profile_card.html.erb
<%= link_to profile_path user do %>
  <div class="card">
    <div class="card-body" style="padding:6px">
      <div class="container" style="padding:0px">
        <div class="row">
          <div class="col-4">
            <%= image_tag("profile.jpg", width: "100%") %>
          </div>
          <div class="col">
            <h5 class="card-title" style="margin:4px"> <%= user.id %> <%= user.first_name %> <%= user.last_name %></h5>
            <p class="card-text"> <%= user.about_me %> </p>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <p class="card-text">
              <% user.user_skills.each do |user_skill| %>
                <%= user_skill.skill.title %> -
              <% end %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/profiles/_search_result.html.erb
<% @users.each do |user| %>
  <%= render "profiles/profile_card", user: user %>
<% end %>

app/views/profiles/index.html.erb
<%= form_with url: test_profiles_path, method: :post do |form|%>
  <div class="mb-3">
    <%= form.collection_select :skill_id, Skill.all, :id, :title, {},
    { class: "form-select" , onchange: 'this.form.requestSubmit()'} %>
  </div>
<% end %>

<div id="users">
  <% @users.each do |user| %>
    <%= render "profile_card", user: user %>
  <% end %>
</div>
<br><br>

app/views/profiles/show.html.erb
<div class="mb-2">
  <%= render "profile_card", user: @user %>
</div>

<div class="container" style="padding:0px">
  <div class="row">

    <div class="col">
      <div class="mb">
        <span class="material-icons">mail</span> <%= mail_to @user.email %>
      </div>
    </div>

    <div class="col">
      <div class="mb">
        <span class="material-icons">phone</span> <%= phone_to @user.phone_number %>
      </div>
    </div>

  </div>
</div>

app/views/user_skills/_form.html.erb
<%= form_with(model: user_skill) do |form| %>
  <% if user_skill.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_skill.errors.count, "error") %> prohibited this user_skill from being saved:</h2>

      <ul>
        <% user_skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-group mb-3">
    <%= form.number_field :user_id, id: :story_user_id, value: current_user.id, type: :hidden %>
    <%= form.collection_select :skill_id, Skill.all, :id, :title, {}, { class: "form-select" } %>
    <%= form.submit "Add new skill", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/user_skills/_user_skill.html.erb
<div id="<%= dom_id user_skill %>" class="input-group mb-3">
    <p> <%= user_skill.skill.title %> </p>
  <%= button_to "delete", user_skill, method: :delete, style: "display:inline" %>
</div>

app/views/user_skills/index.html.erb
<h1>My skills</h1>
<br>

<%= render "form", user_skill: UserSkill.new %>
<br>

<div id="user_skills">
  <% if @user_skills %>
    <% @user_skills.each do |user_skill| %>
      <%= render user_skill %>
    <% end %>
  <% end %>
</div>

app/views/users/_user.html.erb
<div class="card mb-3">
  <div class="card-body" style="padding:6px">
    <div class="container" style="padding:0px">
      <div class="row">
        <div class="col-4">
          <%= image_tag("profile.jpg", width: "100%") %>
        </div>
        <div class="col">
          <h6 class="card-title" style="margin:4px; color:black"> <%= user.first_name %> <%= user.last_name %></h6>
          <p class="card-text" style="font-size:0.8em; color:black"> <%= user.about_me %> </p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="mb-1">
  <strong>mail:</strong> <%= user.email %> <br>
</div>

<div class="mb-1">
  <strong>call:</strong> : <%= user.phone_number %>
</div>

app/views/users/_user_card.html.erb
<div class="card">
  <div class="card-body" style="padding:6px">
    <div class="container" style="padding:0px">
      <div class="row">
        <div class="col-4">
          <%= image_tag("profile.jpg", width: "100%") %>
        </div>
        <div class="col">
          <h6 class="card-title" style="margin:4px; color:black"> <%= user.first_name %> <%= user.last_name %></h6>
          <p class="card-text" style="font-size:0.8em; color:black"> <%= user.about_me %> </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user_path user do %>
    <%= render "user_card", user: user %>
  <% end %>
<% end %>
<br><br>

<% if user_signed_in? %>
  hi <%= current_user.attributes %>
<% end %>